dist: xenial
branches:
  only:
  - master
before_install:
  - sudo apt-get -y install libopenmpi-dev
  - sudo apt-get -y install libsdl2-2.0-0
  - sudo apt-get -y install at-spi2-core
  - sudo apt-get -y install libpam-systemd
  - sudo apt-get -y install xauth
  - sudo apt-get -y install xvfb
#  - sudo /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1200x1050x16
sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
#    - python: "3.7"
#      env: TOXENV=lint
#    - python: "3.7"
#      env: TOXENV=cov,report

cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U tox
language: python
before_script:
  - echo "start before_script:"
  - xvfb-run loginctl list-sessions
  - echo "end beefore_script"
script: tox -vvvv
