branches:
  only:
  - master
before_install:
#  - sudo apt-add-repository -y ppa:deadsnakes/ppa
#  - sudo apt-get update
  - sudo apt-get -y install libopenmpi-dev
  - sudo apt-get -y install libsdl2-2.0-0
  - sudo apt-get -y install xvfb herbstluftwm
#  - sudo apt-get -y install jwm
#  - sudo apt-get -y install xinit
#  - sudo apt-get -y install python3.6-dev
#  - sudo apt-get -y install libgtk-3-dev
#  - sudo apt-get -y install libgstreamer1.0-0
#  - sudo apt-get -y install gstreamer1.0-plugins-base
sudo: required
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
#    - python: "3.7"
#      env: TOXENV=lint
#    - python: "3.7"
#      env: TOXENV=cov,report

cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U tox
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac+extension GLX +render -noreset"
  - sleep 3
language: python
before_script:
  - "herbstluftwm &"
  - sleep 1
script: tox -vvvv
#  # Output something every 10 minutes or Travis kills the job
#  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
#  - tox -vvvv
#  # Killing background sleep loop
#  - kill %1