branches:
  only:
  - master
before_install:
  - sudo apt-get -y install libopenmpi-dev
  - sudo apt-get -y install python3.6-dev
  - sudo apt-get -y install libgtk-3-dev
  - sudo apt-get -y install libgstreamer1.0-0
  - sudo apt-get -y install gstreamer1.0-plugins-base
sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
#    - python: "3.7"
#      env: TOXENV=lint
#    - python: "3.7"
#      env: TOXENV=cov,report

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script: tox
