branches:
  only:
  - master
before_install:
  - sudo apt-get -y install libopenmpi-dev
  - sudo apt-get -y install libsdl2-2.0-0
  - sudo apt-get -y install at-spi2-core
  - sudo apt-get -y install xvfb
sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36 ARMI_GUI_TESTS=true
#    - python: "3.7"
#      env: TOXENV=lint
#    - python: "3.7"
#      env: TOXENV=cov,report

cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U tox
language: python
script: tox -vvvv